### ISSUE TITLE
Ingress Web UI is not working (show in sidebar)

### ISSUE THREAD

**Issue by tW4r** [hassio-addons/addon-traccar#15]
# Problem/Motivation

I cannot access traccar web ui provided by the Show in sidebar toggle on hass.io, this is a fresh install. I do not think this is the same as issue #14 as this concerns the Web UI rather than API

## Expected behavior

Accessing traccar web ui via ingress

## Actual behavior

Web UI Shows ` 502: Bad Gateway`

## Steps to reproduce

1. Fresh hass.io install on Raspberry Pi 2B
2. Install traccar through addon store
3. Enable ingress provided Show in sidebar toggle in settings
4. Try to access Web UI from sidebar OR [OPEN WEB UI] button

## Logs

Probably related hass.io logs:
```
ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:65397 ssl:None [Connection refused]
```

**Comment by frenck** [comment]
Please provide add-on logs

**Comment by tW4r** [comment]
Add-on logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Traccar
 Modern GPS Tracking Platform
-----------------------------------------------------------
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi2)
 Home Assistant version: 0.95.4
 Supervisor version: 167
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] traccar.sh: executing... 
[cont-init.d] traccar.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:15:03] INFO: Starting Traccar server...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/traccar/lib/slf4j-jdk14-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/traccar/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
2019-07-08 20:15:16  INFO: HikariPool-1 - Starting...
2019-07-08 20:15:21  INFO: HikariPool-1 - Start completed.
2019-07-08 20:15:37  INFO: Clearing database change log checksums
2019-07-08 20:15:39  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
2019-07-08 20:15:39  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
2019-07-08 20:15:39  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2019-07-08 20:15:39  INFO: Waiting for changelog lock....
<... SELECT LOCKED and waiting for changelock ...>
2019-07-08 20:20:30  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2019-07-08 20:20:30  INFO: Waiting for changelog lock....
2019-07-08 20:20:40  INFO: SELECT ID,LOCKED,LOCKGRANTED,LOCKEDBY FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2019-07-08 20:20:40 ERROR: Main method error - Could not acquire change log lock.  Currently locked by homeassistant (172.30.32.1) since 7/7/19 3:25 PM - LockException (... < DataManager:310 < *:90 < Context:292 < Main:110 < ...)
Exception in thread "main" java.lang.RuntimeException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by homeassistant (172.30.32.1) since 7/7/19 3:25 PM
	at org.traccar.Main.run(Main.java:152)
	at org.traccar.Main.main(Main.java:104)
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by homeassistant (172.30.32.1) since 7/7/19 3:25 PM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:230)
	at liquibase.Liquibase.clearCheckSums(Liquibase.java:1442)
	at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:310)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:292)
	at org.traccar.Main.run(Main.java:110)
	... 1 more
```
traccar seems to restart after this

**Comment by frenck** [comment]
So the issue it, it won't start, because of a database lock.
This is mainly caused because you are using H2 database.

https://github.com/hassio-addons/addon-traccar#storing-data-in-mysqlmariadb

Also, see step 7 of the installation manual of the add-on.
