### ISSUE TITLE
Addon broken after latest v0.15.0 update

### ISSUE THREAD

**Issue by martinhoess** [hassio-addons/addon-traccar#169]
# Problem/Motivation

After the latest update the Addon won't start anymore. This results in a high CPU load from the java process.
`Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write f                                                                                                                          ormat 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
        at org.h2.message.DbException.get(DbException.java:216)
        at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
        at org.h2.mvstore.db.Store.<init>(Store.java:140)
        at org.h2.engine.Database.<init>(Database.java:324)
        at org.h2.engine.Engine.openSession(Engine.java:92)
        at org.h2.engine.Engine.openSession(Engine.java:222)
        at org.h2.engine.Engine.createSession(Engine.java:201)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.jav                                                                                                                          a:338)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
        at org.h2.Driver.connect(Driver.java:59)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSourc                                                                                                                          e.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470                                                                                                                          )
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        ... 7 more`

It seems that there is a database update/migration needed
https://www.traccar.org/forums/topic/server-upgrade-traccar-wont-start-anymore/
https://www.traccar.org/forums/topic/error-to-update-to-415/#post-68319

I am aware that it is actually a problem of Traccar itself. 
But the addon should actually perform the migration during the update or there should be a separate description for HA/addon how to perform the migration manually.

## Expected behavior

upgrade from <0.15.0 to >= 0.15.0 with out breakting the addon

## Actual behavior

addon won't start and produce high cpu load

## Steps to reproduce

Install version <0.15.0 produce some data -> update to version 0.15.0

## Proposed changes

Database update/migration at first start of version 0.15.0

**Comment by emiel-qx** [comment]
Same problem here. 

- Add-on CPU-gebruik
95.6 % (restart loop addon?)

- Opening the web gui results in a 502 bad gateway error

-  [13:00:51] INFO: Starting Traccar server...
2022-01-21 13:00:54  INFO: HikariPool-1 - Starting...
2022-01-21 13:00:56 ERROR: HikariPool-1 - Exception during pool initialization. - The write format 1 is smaller than the supported format 2 [2.0.206/5] - MVStoreException (... < DataManager:131 < *:90 < Context:298 < Main:120 < ...)
2022-01-21 13:00:56 ERROR: Main method error - The write format 1 is smaller than the supported format 2 [2.0.206/5] - MVStoreException (... < DataManager:131 < *:90 < Context:298 < Main:120 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "The write format 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
	at org.traccar.Main.run(Main.java:147)
	at org.traccar.Main.main(Main.java:106)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "The write format 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:298)
	at org.traccar.Main.run(Main.java:120)
	... 1 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
	at org.h2.mvstore.db.Store.<init>(Store.java:140)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 2 [2.0.206/5]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:878)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:455)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	... 19 more

**Comment by sanderlv** [comment]
Mine is broken as well... I get this:

```
[16:34:03] INFO: Starting Traccar server...
2022-02-21 16:34:04  INFO: HikariPool-1 - Starting...
2022-02-21 16:34:05 ERROR: HikariPool-1 - Exception during pool initialization. - The write format 1 is smaller than the supported format 2 [2.0.206/5] - MVStoreException (... < DataManager:131 < *:90 < Context:298 < Main:120 < ...)
2022-02-21 16:34:05 ERROR: Main method error - The write format 1 is smaller than the supported format 2 [2.0.206/5] - MVStoreException (... < DataManager:131 < *:90 < Context:298 < Main:120 < ...)
Exception in thread "main" java.lang.RuntimeException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "The write format 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
	at org.traccar.Main.run(Main.java:147)
	at org.traccar.Main.main(Main.java:106)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "The write format 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.traccar.database.DataManager.initDatabase(DataManager.java:131)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:298)
	at org.traccar.Main.run(Main.java:120)
	... 1 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.0.206/5]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
	at org.h2.mvstore.db.Store.<init>(Store.java:140)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 7 more
Caused by: org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 2 [2.0.206/5]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:878)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:455)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	... 19 more
```

**Comment by emiel-qx** [comment]
I fixed it by installing MariaDB addon. After a restart you can setup
Traccar again.

Op ma 21 feb. 2022 16:35 schreef Sender ***@***.***>:

**Comment by sanderlv** [comment]
Mariadb addon? How come that has to do with? It's  a separate addon...?

**Comment by emiel-qx** [comment]
True, but Traccar needs a separate database to function properly.

Op ma 21 feb. 2022 16:46 schreef Sender ***@***.***>:

**Comment by sanderlv** [comment]
Mine never did. As I use as a separate addon I also don't want it...

**Comment by tjorim** [comment]
> Mine never did. As I use as a separate addon I also don't want it...

Yeah well, too bad. It's literally step 1 of the installation guide.
`Ensure you have the official "MariaDB" add-on installed and running!`

**Comment by sanderlv** [comment]
You are right 🙈. I had deleted it awhipeago since I thought I did not use it anymore

**Comment by frenck** [comment]
Yep, this is caused by missing the first step of the manual:

![image](https://user-images.githubusercontent.com/195327/159563716-4a0e55d2-aa66-430e-9099-ab443e5c0e6d.png)

This has been in there for a long long time already.

**Comment by sanderlv** [comment]
Indeed. Installed loooooong time ago. And then I decided I did not need maria anymore...
Would be good to warn upon removal it is there for a dependance reason. (My synology package manager does that)

**Comment by frenck** [comment]
> Would be good to warn upon removal it is there for a dependance reason. (My synology package manager does that)

That is a nice suggestion for the Home Assistant project, but is not something an add-on can do or provide right now.
