### ISSUE TITLE
ERROR_INJECTING_CONSTRUCTOR

### ISSUE THREAD

**Issue by Szyba56** [hassio-addons/addon-traccar#263]
Hello
After the last update, I have a constant error and I cannot run the add-on.

1) [Guice/ErrorInjectingConstructor]: FileNotFoundException: /config/hassio.xml (No such file or directory)
  at Config.<init>(Config.java:42)
  at MainModule.configure(MainModule.java:116)
  while locating Config

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Config:                "org.traccar.config.Config"
FileNotFoundException: "java.io.FileNotFoundException"
MainModule:            "org.traccar.MainModule"
========================
End of classname legend:
========================

	at org.traccar.Main.run(Main.java:154)
	at org.traccar.Main.main(Main.java:114)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: FileNotFoundException: /config/hassio.xml (No such file or directory)
  at Config.<init>(Config.java:42)
  at MainModule.configure(MainModule.java:116)
  while locating Config

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Config:                "org.traccar.config.Config"
FileNotFoundException: "java.io.FileNotFoundException"
MainModule:            "org.traccar.MainModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.traccar.Main.run(Main.java:120)
	... 1 more
Caused by: java.io.FileNotFoundException: /config/hassio.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at org.traccar.config.Config.<init>(Config.java:51)
	at org.traccar.config.Config$$FastClassByGuice$$933051.GUICE$TRAMPOLINE(<generated>)
	at org.traccar.config.Config$$FastClassByGuice$$933051.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)

**Comment by trihatmaja** [comment]
Hi, add the traccar xml file to the hassio config directory

This is the xml: https://github.com/hassio-addons/addon-traccar/blob/main/traccar/rootfs/etc/traccar/traccar.xml
if you install the File Editor Add-On, just create new file 'traccar.xml' and copy paste the xml there.

**Comment by AZgeekster** [comment]
I updated traccar and I am getting the same error as OP. Uninstalled and reinstalled traccar and same error about hassio.xml not found.

**Comment by AZgeekster** [comment]
> I updated traccar and I am getting the same error as OP. Uninstalled and reinstalled traccar and same error about hassio.xml not found.

Found a fix for me.
This file: addon_configs/a0d7b954_traccar/traccar.xml
Line 10 (incorrect):     <entry key='config.default'>/etc/hassio.xml</entry>

Changed the directory listing to the correct location.
    <entry key='config.default'>/homeassistant/hassio.xml</entry>

Now traccar server is starting and working for me. Hope this helps
