### ISSUE TITLE
Error setting up platform legacy traccar

### ISSUE THREAD

**Issue by lor74** [hassio-addons/addon-traccar#277]
# Problem/Motivation

Unable to setup traccar device tracker

## Expected behavior

Traccar device tracker show my devices

## Actual behavior

No devices found for traccar device_tracker

## Steps to reproduce

After traccar and mariadb add-ons installation, restart core and got this error

Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:307
Integration: Localizzatore di dispositivo ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 20:52:53 (1 occurrences)
Last logged: 20:52:53
Error setting up platform legacy traccar
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pytraccar/client.py", line 60, in _call_api
    async with self._client_session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 541, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 330, in __init__
    self.update_auth(auth, trust_env)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 538, in update_auth
    self.headers[hdrs.AUTHORIZATION] = auth.encode()
                                       ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 174, in encode
    creds = (f"{self.login}:{self.password}").encode(self.encoding)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201d' in position 34: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 307, in async_setup_legacy
    setup = await self.platform.async_setup_scanner(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/traccar/device_tracker.py", line 202, in async_setup_scanner
    return await scanner.async_init()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/traccar/device_tracker.py", line 238, in async_init
    await self._api.get_server()
  File "/usr/local/lib/python3.11/site-packages/pytraccar/client.py", line 92, in get_server
    response: ServerModel = await self._call_api("server")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytraccar/client.py", line 88, in _call_api
    raise TraccarException(f"Unexpected error - {exception}") from exception
pytraccar.exceptions.TraccarException: Unexpected error - 'latin-1' codec can't encode character '\u201d' in position 34: ordinal not in range(256)
```

**Comment by lor74** [comment]
Hi, thanks for quick reply... and sorry for missunderstanding.

**Comment by frenck** [comment]
Don't worry about it!

I hope you'll find a solution for your issue 👍 

../Frenck
